#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#
#
# docker-compose -f docker-compose-origin.yml up

version: '3.8'

networks:
  pulsar:
    driver: bridge

services:

  zk1:
    container_name: zk1
    hostname: origin.pulsar.com
    ports:
     - "192.168.0.131:2181:2181"
    image: apachepulsar/pulsar-all:3.0.0
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
               bin/apply-config-from-env.py conf/pulsar_env.sh && \
               bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
               exec bin/pulsar zookeeper"
    environment:
      ZOOKEEPER_SERVERS: zk1,zk2,zk3
      ZK_ID: 1
      PULSAR_ZK_CONF: /conf/zookeeper.conf
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    networks:
      pulsar:

  zk2:
    container_name: zk2
    hostname: origin.pulsar.com
    ports:
     - "192.168.0.131:2182:2181"
    image: apachepulsar/pulsar-all:3.0.0
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
               bin/apply-config-from-env.py conf/pulsar_env.sh && \
               bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
               exec bin/pulsar zookeeper"
    environment:
      ZOOKEEPER_SERVERS: zk1,zk2,zk3
      ZK_ID: 2
      PULSAR_ZK_CONF: /conf/zookeeper.conf
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    networks:
      pulsar:

  zk3:
    container_name: zk3
    hostname: origin.pulsar.com
    ports:
     - "192.168.0.131:2183:2181"
    image: apachepulsar/pulsar-all:3.0.0
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf && \
               bin/apply-config-from-env.py conf/pulsar_env.sh && \
               bin/generate-zookeeper-config.sh conf/zookeeper.conf && \
               exec bin/pulsar zookeeper"
    environment:
      ZOOKEEPER_SERVERS: zk1,zk2,zk3
      ZK_ID: 3
      PULSAR_ZK_CONF: /conf/zookeeper.conf
    volumes:
      - ./conf:/conf
      - ./scripts:/scripts
    networks:
      pulsar:
  
  bk1:
    hostname: origin.pulsar.com
    ports:
      - "192.168.0.131:3181:3181"
    container_name: bk1
    image: apachepulsar/pulsar-all:3.0.0
    command: >
      bash -c "export dbStorage_writeCacheMaxSizeMb="$${dbStorage_writeCacheMaxSizeMb:-16}" && \
               export dbStorage_readAheadCacheMaxSizeMb="$${dbStorage_readAheadCacheMaxSizeMb:-16}" && \
               bin/apply-config-from-env.py conf/bookkeeper.conf && \
               bin/apply-config-from-env.py conf/pulsar_env.sh && \
               bin/watch-znode.py -z $$zkServers -p /initialized-$$clusterName -w && \
               exec bin/pulsar bookie"
    environment:
      clusterName: test
      zkServers: zk1,zk2,zk3
      numAddWorkerThreads: 8
      useHostNameAsBookieID: "true"
    volumes:
      - ./scripts/apply-config-from-env.py:/pulsar/bin/apply-config-from-env.py:z
    depends_on:
      - zk1
      - zk2
      - zk3      
    networks:
      pulsar:

  bk2:
    hostname: origin.pulsar.com
    ports:
      - "192.168.0.131:3182:3181"
    container_name: bk2
    image: apachepulsar/pulsar-all:3.0.0
    command: >
      bash -c "export dbStorage_writeCacheMaxSizeMb="${dbStorage_writeCacheMaxSizeMb:-16}" && \
               export dbStorage_readAheadCacheMaxSizeMb="${dbStorage_readAheadCacheMaxSizeMb:-16}" && \
               bin/apply-config-from-env.py conf/bookkeeper.conf && \
               bin/apply-config-from-env.py conf/pulsar_env.sh && \
               bin/watch-znode.py -z $$zkServers -p /initialized-$$clusterName -w && \
               exec bin/pulsar bookie"
    environment:
      clusterName: test
      zkServers: zk1,zk2,zk3
      numAddWorkerThreads: 8
      useHostNameAsBookieID: "true"
    volumes:
      - ./scripts/apply-config-from-env.py:/pulsar/bin/apply-config-from-env.py:z
    depends_on:
      - bk1
    networks:
      pulsar:

  bk3:
    hostname: origin.pulsar.com
    ports:
      - "192.168.0.131:3183:3181"
    container_name: bk3
    image: apachepulsar/pulsar-all:latest
    command: >
      bash -c "export dbStorage_writeCacheMaxSizeMb="${dbStorage_writeCacheMaxSizeMb:-16}" && \
               export dbStorage_readAheadCacheMaxSizeMb="${dbStorage_readAheadCacheMaxSizeMb:-16}" && \
               bin/apply-config-from-env.py conf/bookkeeper.conf && \
               bin/apply-config-from-env.py conf/pulsar_env.sh && \
               bin/watch-znode.py -z $$zkServers -p /initialized-$$clusterName -w && \
               exec bin/pulsar bookie"
    environment:
      clusterName: test
      zkServers: zk1,zk2,zk3
      numAddWorkerThreads: 8
      useHostNameAsBookieID: "true"
    volumes:
      - ./scripts/apply-config-from-env.py:/pulsar/bin/apply-config-from-env.py:z
    depends_on:
      - bk1
    networks:
      pulsar: